### ISSUE TITLE
Milestones for the beginning

### ISSUE THREAD

**Issue by Sunconure11** [Um-Mitternacht/George-Washington-Carver-1.7#5]
Fire reduces everything to ashes, which become part of the earth again and will serve to nourish life.

https://en.wikipedia.org/wiki/Boscia_senegalensis

https://en.wikipedia.org/wiki/Atya_gabonensis

https://en.wikipedia.org/wiki/Arowana

https://en.wikipedia.org/wiki/Blue_Peacock

https://en.wikipedia.org/wiki/Tsar_Bomba

https://en.wikipedia.org/wiki/1918_New_Year_Honours

https://en.wikipedia.org/wiki/Entropy

https://en.wikipedia.org/wiki/Strangelet

https://en.wikipedia.org/wiki/Grey_goo

https://en.wikipedia.org/wiki/American_cheetah

https://en.wikipedia.org/wiki/Steppe_bison

https://en.wikipedia.org/wiki/Dark_triad

https://en.wikipedia.org/wiki/Reptiliomorpha

https://en.wikipedia.org/wiki/Diplovertebron

https://en.wikipedia.org/wiki/Echo_chamber_(media)

https://en.wikipedia.org/wiki/Tribe_(Internet)

https://en.wikipedia.org/wiki/Tetrapodophis

- [X] ⛤ ♄ ♃
- [ ] Fix up 1.8 and 1.9
- [ ] Remove NEI support and replace it with JEI. In addition, add GUIs for all machines that should have a GUI, such as the cheese vat.
- [ ] Add a guide
- [ ] Port netherloid to latest version, and merge it with main codebase
- [ ] Implementation of wheat?
- [ ] Something here
